Completed bubble_sort and bubble_sort_by
appiersign/bubble-sort pull request #1
Opened 2020-03-20 20:59 UTC by appiersign

in this pull request we:

- defined the bubble_sort and bubble_sort_by functions
- we added a loop to iterate through the array and compare
- we added checks for nil
- we define and block which handled the sorting for bubble_sort_by
- we refactored the if statements to one liners when necesssary

2020-03-20 21:59 UTC, shshamim63 requested changes
## Status :space_invader: Required Changes :space_invader: 
___
Hi @appiersign and @aulbytj :wave: 
Awesome job :clap: , Well descriptive readme and your bubble_sort perform properly. But have found some issues that are blocking me to approve this project now. Please see my comments to resolve the problems.
___
### :spades: Mandatory Changes :spades: 
___
1. It seems that your linter is not working properly. Please check this [link](https://github.com/microverseinc/linters-config/tree/master/ruby)
![image](https://user-images.githubusercontent.com/38625956/77209354-45ac3900-6b28-11ea-91a4-f17d1f044946.png)
2. Your bubble_sort_by is not working properly. Please check the comments below to make it work properly.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-03-20 21:59 UTC, shshamim63 commented on main.rb
> +end
- Bubble sort does not print anything. It just returns a modified arrray.
- While I tried to test your bubble_sort_by with the following code it did not work.
```ruby
bubble_sort_by(%w[hi hello hey]) { |left, right| left.length - right.length }
```
Please resolve the problems.

2020-03-20 23:48 UTC, pelzolga123 requested changes
Project requires changes.

2020-03-20 23:49 UTC, pelzolga123 commented
## Hi Team! ![](https://user-images.githubusercontent.com/38801423/62908122-703d4480-bd44-11e9-9115-42025ab7f341.png)
### You made a good effort, one more thing left:
* [ ] `bubble_sort_by` has the same issue previous review pointed:

```ruby
 bubble_sort_by(%w[hi hello hey]) { |left, right| left.length - right.length }
``` 
should return `["hi", "hey", "hello"]` as a result. Right now it's returning `["hi", "hello", "hey"]`


### Please kindly fix the above issue and send another code review request.

If you have any questions or need help, you can message me on slack (@ Olga Pelts). *Happy coding*

2020-03-21 06:57 UTC, suretrust approved these changes
Hi team, 👋 

### Great job implementing the suggested changes. 🙌 Let's get this merged! 👍 

_Good luck with your future projects and happy coding!_ 🎉

2020-03-21 11:13 UTC, merged